name: Release

on:
  release:
    types: [published]

jobs:
  buildlinux:
    name: "Build Linux Docker"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build Docker Images 
      run: |
        docker build . --file Dockerfile --tag stuartferguson/txnprocbase:latest --tag stuartferguson/txnprocbase:${{ steps.get_version.outputs.VERSION }}

    - name: Publish Images to Docker Hub
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/txnprocbase:latest
        docker push stuartferguson/txnprocbase:${{ steps.get_version.outputs.VERSION }}
   
  buildwindows:
    name: "Build Windows Docker"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get the version
      id: get_version
      uses: battila7/get-version-action@v2
      
    - name: Build Docker Images 
      run: |
        docker build . --file DockerfileWindows --tag stuartferguson/txnprocbasewindows:latest --tag stuartferguson/txnprocbasewindows:${{ steps.get_version.outputs.version }}

    - name: Publish Images to Docker Hub
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/txnprocbasewindows:latest
        docker push stuartferguson/txnprocbasewindows:${{ steps.get_version.outputs.version }}
  
  release:
    if: "!github.event.release.prerelease"
    name: "Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Install Octopus CLI
      run: |
        sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
        curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
        sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
        sudo apt update && sudo apt install octopuscli      

    - name: Pack Files for Octopus
      run: >-
        octo pack
        --outFolder /home/runner/work/SharedConfiguration/SharedConfiguration/deploy
        --basePath /home/runner/work/SharedConfiguration/SharedConfiguration/config
        --id SharedConfiguration
        --version ${{ steps.get_version.outputs.VERSION }}
        --format zip
        --verbose
        --logLevel=verbose        

    - name: Push Package to Octopus
      run: >-
        octo push
        --server ${{ secrets.OCTOPUS_URL }}
        --apiKey ${{ secrets.OCTOPUS_APIKEY }}
        --package /home/runner/work/SharedConfiguration/SharedConfiguration/deploy/SharedConfiguration.${{ steps.get_version.outputs.VERSION }}.zip
        --overwrite-mode IgnoreIfExists        

    - name: Get Release
      id: getrelease
      uses: octokit/request-action@v2.0.17
      with:
          route: GET /repos/TransactionProcessing/SharedConfiguration/releases/tags/${{ steps.get_version.outputs.VERSION }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build Release Notes
      id: buildreleasenotes
      uses: gr2m/get-json-paths-action@v1.0.4
      with:
          json: ${{ steps.getrelease.outputs.data }}
          releasenote: "body"          

    - name: Create & Deploy Release in Octopus
      run: >-
        octo create-release
        --server ${{ secrets.OCTOPUS_URL }}
        --apiKey ${{ secrets.OCTOPUS_APIKEY }}
        --project "Shared Configuration"
        --version ${{ steps.get_version.outputs.VERSION }}
        --channel Default
        --deployTo staging
        --waitfordeployment
        --deploymenttimeout 00:05:00
        --releasenotes "${{ steps.buildreleasenotes.outputs.releasenote }}"
