name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Zip the config files
      uses: papeloto/action-zip@v1
      with:
       files: /home/runner/work/SharedConfiguration/SharedConfiguration/*.json
       dest: result.zip
       
    - name: Debug
      uses: actions/upload-artifact@v1
      with:
       name: my-artifact
       path: ${{ github.workspace }}/result.zip          
